########################################
#
# Makefile for Homework 04
#
# WARNING - DO NOT CHANGE THIS FILE
#
#
########################################

default: attack03 attack13 attack04

attack03: attack03.c
	gcc -o attack03 attack03.c -lcrypto

attack13: attack13.c
		gcc -o attack13 attack13.c -lcrypto

attack04: attack04.c
				gcc -o attack04 attack04.c -lcrypto
